# Generated by Django 2.2.3 on 2019-07-25 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0003_auto_20190725_0711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='slug',
        ),
    ]
