# Generated by Django 2.2.3 on 2019-07-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0004_remove_program_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
