# Generated by Django 2.2.3 on 2019-07-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0005_program_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='slug',
        ),
    ]
